# Stubs for eliot._errors (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

class ErrorExtraction:
    registry: Any = ...
    def __init__(self) -> None: ...
    def register_exception_extractor(self, exception_class: Any, extractor: Any) -> None: ...
    def get_fields_for_exception(self, logger: Any, exception: Any): ...

register_exception_extractor: Any
get_fields_for_exception: Any
