create table "NAACR"."EXTRACT" (
"Record Type" varchar2(1),
"Registry Type" varchar2(1),
"FIN Coding System" varchar2(1),
"Reserved 00" varchar2(13),
"NAACCR Record Version" varchar2(3),
"NPI--Registry ID" varchar2(10),
"Registry ID" varchar2(10),
"Tumor Record Number" varchar2(2),
"Patient ID Number" varchar2(8),
"Patient System ID-Hosp" varchar2(8),
"Reserved 01" varchar2(37),
"Addr at DX--City" varchar2(50),
"Addr at DX--State" varchar2(2),
"Addr at DX--Postal Code" varchar2(9),
"County at DX" varchar2(3),
"Census Tract 1970/80/90" varchar2(6),
"CensusBlockGroup 70/80/90" varchar2(1),
"Census Cod Sys 1970/80/90" varchar2(1),
"Census Tr Cert 1970/80/90" varchar2(1),
"Census Tract 2000" varchar2(6),
"Census Block Group 2000" varchar2(1),
"Census Tr Certainty 2000" varchar2(1),
"Marital Status at DX" varchar2(1),
"Race 1" varchar2(2),
"Race 2" varchar2(2),
"Race 3" varchar2(2),
"Race 4" varchar2(2),
"Race 5" varchar2(2),
"Race Coding Sys--Current" varchar2(1),
"Race Coding Sys--Original" varchar2(1),
"Spanish/Hispanic Origin" varchar2(1),
"Computed Ethnicity" varchar2(1),
"Computed Ethnicity Source" varchar2(1),
"Sex" varchar2(1),
"Age at Diagnosis" varchar2(3),
"Date of Birth" varchar2(8),
"Date of Birth Flag" varchar2(2),
"Birthplace" varchar2(3),
"Occupation Code--Census" varchar2(3),
"Industry Code--Census" varchar2(3),
"Occupation Source" varchar2(1),
"Industry Source" varchar2(1),
"Text--Usual Occupation" varchar2(100),
"Text--Usual Industry" varchar2(100),
"Occup/Ind Coding System" varchar2(1),
"NHIA Derived Hisp Origin" varchar2(1),
"Race--NAPIIA(derived API)" varchar2(2),
"IHS Link" varchar2(1),
"GIS Coordinate Quality" varchar2(2),
"RuralUrban Continuum 1993" varchar2(2),
"RuralUrban Continuum 2003" varchar2(2),
"Census Tract 2010" varchar2(6),
"Census Block Group 2010" varchar2(1),
"Census Tr Certainty 2010" varchar2(1),
"Reserved 02" varchar2(92),
"Sequence Number--Central" varchar2(2),
"Date of Diagnosis" varchar2(8),
"Date of Diagnosis Flag" varchar2(2),
"Primary Site" varchar2(4),
"Laterality" varchar2(1),
"Morph--Type&Behav ICD-O-2" varchar2(5),
"Histology (92-00) ICD-O-2" varchar2(4),
"Behavior (92-00) ICD-O-2" varchar2(1),
"Morph--Type&Behav ICD-O-3" varchar2(5),
"Histologic Type ICD-O-3" varchar2(4),
"Behavior Code ICD-O-3" varchar2(1),
"Grade" varchar2(1),
"Grade Path Value" varchar2(1),
"Grade Path System" varchar2(1),
"Site Coding Sys--Current" varchar2(1),
"Site Coding Sys--Original" varchar2(1),
"Morph Coding Sys--Current" varchar2(1),
"Morph Coding Sys--Originl" varchar2(1),
"Diagnostic Confirmation" varchar2(1),
"Type of Reporting Source" varchar2(1),
"Casefinding Source" varchar2(2),
"Ambiguous Terminology DX" varchar2(1),
"Date of Conclusive DX" varchar2(8),
"Date Conclusive DX Flag" varchar2(2),
"Mult Tum Rpt as One Prim" varchar2(2),
"Date of Multiple Tumors" varchar2(8),
"Date of Mult Tumors Flag" varchar2(2),
"Multiplicity Counter" varchar2(2),
"Reserved 03" varchar2(100),
"NPI--Reporting Facility" varchar2(10),
"Reporting Facility" varchar2(10),
"NPI--Archive FIN" varchar2(10),
"Archive FIN" varchar2(10),
"Accession Number--Hosp" varchar2(9),
"Sequence Number--Hospital" varchar2(2),
"Abstracted By" varchar2(3),
"Date of 1st Contact" varchar2(8),
"Date of 1st Contact Flag" varchar2(2),
"Date of Inpatient Adm" varchar2(8),
"Date of Inpt Adm Flag" varchar2(2),
"Date of Inpatient Disch" varchar2(8),
"Date of Inpt Disch Flag" varchar2(2),
"Inpatient Status" varchar2(1),
"Class of Case" varchar2(2),
"Primary Payer at DX" varchar2(2),
"Reserved 16" varchar2(1),
"RX Hosp--Surg App 2010" varchar2(1),
"RX Hosp--Surg Prim Site" varchar2(2),
"RX Hosp--Scope Reg LN Sur" varchar2(1),
"RX Hosp--Surg Oth Reg/Dis" varchar2(1),
"RX Hosp--Reg LN Removed" varchar2(2),
"RX Hosp--Radiation" varchar2(1),
"RX Hosp--Chemo" varchar2(2),
"RX Hosp--Hormone" varchar2(2),
"RX Hosp--BRM" varchar2(2),
"RX Hosp--Other" varchar2(1),
"RX Hosp--DX/Stg Proc" varchar2(2),
"RX Hosp--Palliative Proc" varchar2(1),
"RX Hosp--Surg Site 98-02" varchar2(2),
"RX Hosp--Scope Reg 98-02" varchar2(1),
"RX Hosp--Surg Oth 98-02" varchar2(1),
"Reserved 04" varchar2(100),
"SEER Summary Stage 2000" varchar2(1),
"SEER Summary Stage 1977" varchar2(1),
"Extent of Disease 10-Dig" varchar2(12),
"EOD--Tumor Size" varchar2(3),
"EOD--Extension" varchar2(2),
"EOD--Extension Prost Path" varchar2(2),
"EOD--Lymph Node Involv" varchar2(1),
"Regional Nodes Positive" varchar2(2),
"Regional Nodes Examined" varchar2(2),
"EOD--Old 13 Digit" varchar2(13),
"EOD--Old 2 Digit" varchar2(2),
"EOD--Old 4 Digit" varchar2(4),
"Coding System for EOD" varchar2(1),
"TNM Edition Number" varchar2(2),
"TNM Path T" varchar2(4),
"TNM Path N" varchar2(4),
"TNM Path M" varchar2(4),
"TNM Path Stage Group" varchar2(4),
"TNM Path Descriptor" varchar2(1),
"TNM Path Staged By" varchar2(1),
"TNM Clin T" varchar2(4),
"TNM Clin N" varchar2(4),
"TNM Clin M" varchar2(4),
"TNM Clin Stage Group" varchar2(4),
"TNM Clin Descriptor" varchar2(1),
"TNM Clin Staged By" varchar2(1),
"Pediatric Stage" varchar2(2),
"Pediatric Staging System" varchar2(2),
"Pediatric Staged By" varchar2(1),
"Tumor Marker 1" varchar2(1)
)
