# Stubs for luigi (Python 3.5)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from luigi import task as task
from luigi.task import Task as Task, Config as Config, ExternalTask as ExternalTask, WrapperTask as WrapperTask, namespace as namespace, auto_namespace as auto_namespace
from luigi import target as target
from luigi.target import Target as Target
from luigi import local_target as local_target
from luigi.local_target import LocalTarget as LocalTarget
from luigi import rpc as rpc
from luigi.rpc import RemoteScheduler as RemoteScheduler, RPCError as RPCError
from luigi import parameter as parameter
from luigi.parameter import Parameter as Parameter, DateParameter as DateParameter, MonthParameter as MonthParameter, YearParameter as YearParameter, DateHourParameter as DateHourParameter, DateMinuteParameter as DateMinuteParameter, DateSecondParameter as DateSecondParameter, DateIntervalParameter as DateIntervalParameter, TimeDeltaParameter as TimeDeltaParameter, IntParameter as IntParameter, FloatParameter as FloatParameter, BoolParameter as BoolParameter, TaskParameter as TaskParameter, EnumParameter as EnumParameter, DictParameter as DictParameter, ListParameter as ListParameter, TupleParameter as TupleParameter, NumericalParameter as NumericalParameter, ChoiceParameter as ChoiceParameter
from luigi import configuration as configuration
from luigi import interface as interface
from luigi.interface import run as run, build as build
from luigi import event as event
from luigi.event import Event as Event
from .tools import range as range
