# Stubs for luigi.configuration (Python 3.5)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any, Optional
# py2: from ConfigParser import ConfigParser
from configparser import ConfigParser

class LuigiConfigParser(ConfigParser):
    NO_DEFAULT = ...  # type: Any
    config_file = ...  # type: Any
    @classmethod
    def add_config_path(cls, path): ...
    @classmethod
    def instance(cls, *args, **kwargs): ...
    @classmethod
    def reload(cls): ...
    # avoid: Signature of "get" incompatible with supertype "Mapping"
    def get(self, section, option, default: Any = ..., **kwargs): ...  # type:ignore
    def getboolean(self, section, option, default: Any = ...): ...  # type:ignore
    def getint(self, section, option, default: Any = ...): ...  # type:ignore
    def getfloat(self, section, option, default: Any = ...): ...  # type:ignore
    def getintdict(self, section): ...
    def set(self, section, option, value: Optional[Any] = ...): ...

def get_config(): ...
