# Stubs for luigi.rpc (Python 3.5)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any, Optional

HAS_UNIX_SOCKET = ...  # type: bool
HAS_REQUESTS = ...  # type: bool
logger = ...  # type: Any

class RPCError(Exception):
    sub_exception = ...  # type: Any
    def __init__(self, message, sub_exception: Optional[Any] = ...) -> None: ...

class URLLibFetcher:
    raises = ...  # type: Any
    def fetch(self, full_url, body, timeout): ...

class RequestsFetcher:
    raises = ...  # type: Any
    session = ...  # type: Any
    def __init__(self, session) -> None: ...
    def fetch(self, full_url, body, timeout): ...

class RemoteScheduler:
    def __init__(self, url: str = ..., connect_timeout: Optional[Any] = ...) -> None: ...
