# Stubs for eliot (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from ._action import Action as Action, current_action as current_action, log_call as log_call, preserve_context as preserve_context, startTask as startTask, start_action as start_action
from ._errors import register_exception_extractor as register_exception_extractor
from ._message import Message as Message
from ._output import FileDestination as FileDestination, ILogger as ILogger, Logger as Logger, MemoryLogger as MemoryLogger, to_file as to_file
from ._traceback import writeFailure as writeFailure, write_traceback as write_traceback
from ._validation import ActionType as ActionType, Field as Field, MessageType as MessageType, ValidationError as ValidationError, fields as fields
from typing import Any

def add_destination(destination: Any) -> None: ...
def use_asyncio_context() -> None: ...
addDestination = add_destination
removeDestination: Any
addGlobalFields: Any
writeTraceback = write_traceback
startAction = start_action
start_task = startTask
write_failure = writeFailure
add_destinations: Any
remove_destination = removeDestination
add_global_fields = addGlobalFields

# Names in __all__ with no definition:
#   __version__
#   _parse
