create table "NAACR"."EXTRACT" (case_index integer,
"Record Type" varchar2(1),
"Registry Type" varchar2(1),
"FIN Coding System" varchar2(1),
"Reserved 00" varchar2(13),
"NAACCR Record Version" varchar2(3),
"NPI--Registry ID" varchar2(10),
"Registry ID" varchar2(10),
"Tumor Record Number" varchar2(2),
"Patient ID Number" varchar2(8),
"Patient System ID-Hosp" varchar2(8),
"Reserved 01" varchar2(37),
"Addr at DX--City" varchar2(50),
"Addr at DX--State" varchar2(2),
"Addr at DX--Postal Code" varchar2(9),
"County at DX" varchar2(3),
"Census Tract 1970/80/90" varchar2(6),
"CensusBlockGroup 70/80/90" varchar2(1),
"Census Cod Sys 1970/80/90" varchar2(1),
"Census Tr Cert 1970/80/90" varchar2(1),
"Census Tract 2000" varchar2(6),
"Census Block Group 2000" varchar2(1),
"Census Tr Certainty 2000" varchar2(1),
"Marital Status at DX" varchar2(1),
"Race 1" varchar2(2),
"Race 2" varchar2(2),
"Race 3" varchar2(2),
"Race 4" varchar2(2),
"Race 5" varchar2(2),
"Race Coding Sys--Current" varchar2(1),
"Race Coding Sys--Original" varchar2(1),
"Spanish/Hispanic Origin" varchar2(1),
"Computed Ethnicity" varchar2(1),
"Computed Ethnicity Source" varchar2(1),
"Sex" varchar2(1),
"Age at Diagnosis" varchar2(3),
"Date of Birth" varchar2(8),
"Date of Birth Flag" varchar2(2),
"Birthplace" varchar2(3),
"Occupation Code--Census" varchar2(3),
"Industry Code--Census" varchar2(3),
"Occupation Source" varchar2(1),
"Industry Source" varchar2(1),
"Text--Usual Occupation" varchar2(100),
"Text--Usual Industry" varchar2(100),
"Occup/Ind Coding System" varchar2(1),
"NHIA Derived Hisp Origin" varchar2(1),
"Race--NAPIIA(derived API)" varchar2(2),
"IHS Link" varchar2(1),
"GIS Coordinate Quality" varchar2(2),
"RuralUrban Continuum 1993" varchar2(2),
"RuralUrban Continuum 2003" varchar2(2),
"Census Tract 2010" varchar2(6),
"Census Block Group 2010" varchar2(1),
"Census Tr Certainty 2010" varchar2(1),
"Reserved 02" varchar2(92),
"Sequence Number--Central" varchar2(2),
"Date of Diagnosis" varchar2(8),
"Date of Diagnosis Flag" varchar2(2),
"Primary Site" varchar2(4),
"Laterality" varchar2(1),
"Morph--Type&Behav ICD-O-2" varchar2(5),
"Histology (92-00) ICD-O-2" varchar2(4),
"Behavior (92-00) ICD-O-2" varchar2(1),
"Morph--Type&Behav ICD-O-3" varchar2(5),
"Histologic Type ICD-O-3" varchar2(4),
"Behavior Code ICD-O-3" varchar2(1),
"Grade" varchar2(1),
"Grade Path Value" varchar2(1),
"Grade Path System" varchar2(1),
"Site Coding Sys--Current" varchar2(1),
"Site Coding Sys--Original" varchar2(1),
"Morph Coding Sys--Current" varchar2(1),
"Morph Coding Sys--Originl" varchar2(1),
"Diagnostic Confirmation" varchar2(1),
"Type of Reporting Source" varchar2(1),
"Casefinding Source" varchar2(2),
"Ambiguous Terminology DX" varchar2(1),
"Date of Conclusive DX" varchar2(8),
"Date Conclusive DX Flag" varchar2(2),
"Mult Tum Rpt as One Prim" varchar2(2),
"Date of Multiple Tumors" varchar2(8),
"Date of Mult Tumors Flag" varchar2(2),
"Multiplicity Counter" varchar2(2),
"Reserved 03" varchar2(100),
"NPI--Reporting Facility" varchar2(10),
"Reporting Facility" varchar2(10),
"NPI--Archive FIN" varchar2(10),
"Archive FIN" varchar2(10),
"Accession Number--Hosp" varchar2(9),
"Sequence Number--Hospital" varchar2(2),
"Abstracted By" varchar2(3),
"Date of 1st Contact" varchar2(8),
"Date of 1st Contact Flag" varchar2(2),
"Date of Inpatient Adm" varchar2(8),
"Date of Inpt Adm Flag" varchar2(2),
"Date of Inpatient Disch" varchar2(8),
"Date of Inpt Disch Flag" varchar2(2),
"Inpatient Status" varchar2(1),
"Class of Case" varchar2(2),
"Primary Payer at DX" varchar2(2),
"Reserved 16" varchar2(1),
"RX Hosp--Surg App 2010" varchar2(1),
"RX Hosp--Surg Prim Site" varchar2(2),
"RX Hosp--Scope Reg LN Sur" varchar2(1),
"RX Hosp--Surg Oth Reg/Dis" varchar2(1),
"RX Hosp--Reg LN Removed" varchar2(2),
"17" varchar2(2450),
"RX Hosp--Radiation" varchar2(1),
"RX Hosp--Chemo" varchar2(2),
"RX Hosp--Hormone" varchar2(2),
"RX Hosp--BRM" varchar2(2),
"RX Hosp--Other" varchar2(1),
"RX Hosp--DX/Stg Proc" varchar2(2),
"RX Hosp--Palliative Proc" varchar2(1),
"RX Hosp--Surg Site 98-02" varchar2(2),
"RX Hosp--Scope Reg 98-02" varchar2(1),
"RX Hosp--Surg Oth 98-02" varchar2(1),
"Reserved 04" varchar2(100),
"SEER Summary Stage 2000" varchar2(1),
"SEER Summary Stage 1977" varchar2(1),
"Extent of Disease 10-Dig" varchar2(12),
"EOD--Tumor Size" varchar2(3),
"EOD--Extension" varchar2(2),
"EOD--Extension Prost Path" varchar2(2),
"EOD--Lymph Node Involv" varchar2(1),
"Regional Nodes Positive" varchar2(2),
"Regional Nodes Examined" varchar2(2),
"EOD--Old 13 Digit" varchar2(13),
"EOD--Old 2 Digit" varchar2(2),
"EOD--Old 4 Digit" varchar2(4),
"Coding System for EOD" varchar2(1),
"TNM Edition Number" varchar2(2),
"TNM Path T" varchar2(4),
"TNM Path N" varchar2(4),
"TNM Path M" varchar2(4),
"TNM Path Stage Group" varchar2(4),
"TNM Path Descriptor" varchar2(1),
"TNM Path Staged By" varchar2(1),
"TNM Clin T" varchar2(4),
"TNM Clin N" varchar2(4),
"TNM Clin M" varchar2(4),
"TNM Clin Stage Group" varchar2(4),
"TNM Clin Descriptor" varchar2(1),
"TNM Clin Staged By" varchar2(1),
"Pediatric Stage" varchar2(2),
"Pediatric Staging System" varchar2(2),
"Pediatric Staged By" varchar2(1),
"Tumor Marker 1" varchar2(1),
"Tumor Marker 2" varchar2(1),
"Tumor Marker 3" varchar2(1),
"Lymph-vascular Invasion" varchar2(1),
"CS Tumor Size" varchar2(3),
"CS Extension" varchar2(3),
"CS Tumor Size/Ext Eval" varchar2(1),
"CS Lymph Nodes" varchar2(3),
"CS Lymph Nodes Eval" varchar2(1),
"CS Mets at DX" varchar2(2),
"CS Mets Eval" varchar2(1),
"CS Mets at Dx-Bone" varchar2(1),
"CS Mets at Dx-Brain" varchar2(1),
"CS Mets at Dx-Liver" varchar2(1),
"CS Mets at Dx-Lung" varchar2(1),
"CS Site-Specific Factor 1" varchar2(3),
"CS Site-Specific Factor 2" varchar2(3),
"CS Site-Specific Factor 3" varchar2(3),
"CS Site-Specific Factor 4" varchar2(3),
"CS Site-Specific Factor 5" varchar2(3),
"CS Site-Specific Factor 6" varchar2(3),
"CS Site-Specific Factor 7" varchar2(3),
"CS Site-Specific Factor 8" varchar2(3),
"CS Site-Specific Factor 9" varchar2(3),
"CS Site-Specific Factor10" varchar2(3),
"CS Site-Specific Factor11" varchar2(3),
"CS Site-Specific Factor12" varchar2(3),
"CS Site-Specific Factor13" varchar2(3),
"CS Site-Specific Factor14" varchar2(3),
"CS Site-Specific Factor15" varchar2(3),
"CS Site-Specific Factor16" varchar2(3),
"CS Site-Specific Factor17" varchar2(3),
"CS Site-Specific Factor18" varchar2(3),
"CS Site-Specific Factor19" varchar2(3),
"CS Site-Specific Factor20" varchar2(3),
"CS Site-Specific Factor21" varchar2(3),
"CS Site-Specific Factor22" varchar2(3),
"CS Site-Specific Factor23" varchar2(3),
"CS Site-Specific Factor24" varchar2(3),
"CS Site-Specific Factor25" varchar2(3),
"CS PreRx Tumor Size" varchar2(3),
"CS PreRx Extension" varchar2(3),
"CS PreRx Tum Sz/Ext Eval" varchar2(1),
"CS PreRx Lymph Nodes" varchar2(3),
"CS PreRx Reg Nodes Eval" varchar2(1),
"CS PreRx Mets at DX" varchar2(2),
"CS PreRx Mets Eval" varchar2(1),
"CS PostRx Tumor Size" varchar2(3),
"CS PostRx Extension" varchar2(3),
"CS PostRx Lymph Nodes" varchar2(3),
"CS PostRx Mets at DX" varchar2(2),
"Derived AJCC-6 T" varchar2(2),
"Derived AJCC-6 T Descript" varchar2(1),
"Derived AJCC-6 N" varchar2(2),
"Derived AJCC-6 N Descript" varchar2(1),
"Derived AJCC-6 M" varchar2(2),
"Derived AJCC-6 M Descript" varchar2(1),
"Derived AJCC-6 Stage Grp" varchar2(2),
"Derived AJCC-7 T" varchar2(3),
"Derived AJCC-7 T Descript" varchar2(1),
"Derived AJCC-7 N" varchar2(3),
"Derived AJCC-7 N Descript" varchar2(1),
"Derived AJCC-7 M" varchar2(3),
"Derived AJCC-7 M Descript" varchar2(1),
"Derived AJCC-7 Stage Grp" varchar2(3),
"Derived PreRx-7 T" varchar2(3),
"Derived PreRx-7 T Descrip" varchar2(1),
"Derived PreRx-7 N" varchar2(3),
"Derived PreRx-7 N Descrip" varchar2(1),
"Derived PreRx-7 M" varchar2(3),
"Derived PreRx-7 M Descrip" varchar2(1),
"Derived PreRx-7 Stage Grp" varchar2(3),
"Derived PostRx-7 T" varchar2(3),
"Derived PostRx-7 N" varchar2(3),
"Derived PostRx-7 M" varchar2(2),
"Derived PostRx-7 Stge Grp" varchar2(3),
"Derived SS1977" varchar2(1),
"Derived SS2000" varchar2(1),
"Derived Neoadjuv Rx Flag" varchar2(1),
"Derived AJCC--Flag" varchar2(1),
"Derived SS1977--Flag" varchar2(1),
"Derived SS2000--Flag" varchar2(1),
"CS Version Input Current" varchar2(6),
"CS Version Input Original" varchar2(6),
"CS Version Derived" varchar2(6),
"SEER Site-Specific Fact 1" varchar2(1),
"SEER Site-Specific Fact 2" varchar2(1),
"SEER Site-Specific Fact 3" varchar2(1),
"SEER Site-Specific Fact 4" varchar2(1),
"SEER Site-Specific Fact 5" varchar2(1),
"SEER Site-Specific Fact 6" varchar2(1),
"ICD Revision Comorbid" varchar2(1),
"Comorbid/Complication 1" varchar2(5),
"Comorbid/Complication 2" varchar2(5),
"Comorbid/Complication 3" varchar2(5),
"Comorbid/Complication 4" varchar2(5),
"Comorbid/Complication 5" varchar2(5),
"Comorbid/Complication 6" varchar2(5),
"Comorbid/Complication 7" varchar2(5),
"Comorbid/Complication 8" varchar2(5),
"Comorbid/Complication 9" varchar2(5),
"Comorbid/Complication 10" varchar2(5),
"Reserved 05" varchar2(200),
"Date of Initial RX--SEER" varchar2(8),
"Date of Initial RX Flag" varchar2(2),
"Date of 1st Crs RX--CoC" varchar2(8),
"Date of 1st Crs Rx Flag" varchar2(2),
"RX Date--Surgery" varchar2(8),
"RX Date--Surgery Flag" varchar2(2),
"RX Date--Most Defin Surg" varchar2(8),
"RX Date Mst Defn Srg Flag" varchar2(2),
"RX Date--Surgical Disch" varchar2(8),
"RX Date Surg Disch Flag" varchar2(2),
"RX Date--Radiation" varchar2(8),
"RX Date--Radiation Flag" varchar2(2),
"RX Date--Radiation Ended" varchar2(8),
"RX Date Rad Ended Flag" varchar2(2),
"RX Date--Systemic" varchar2(8),
"RX Date Systemic Flag" varchar2(2),
"RX Date--Chemo" varchar2(8),
"RX Date--Chemo Flag" varchar2(2),
"RX Date--Hormone" varchar2(8),
"RX Date--Hormone Flag" varchar2(2),
"RX Date--BRM" varchar2(8),
"RX Date--BRM Flag" varchar2(2),
"RX Date--Other" varchar2(8),
"RX Date--Other Flag" varchar2(2),
"RX Date--DX/Stg Proc" varchar2(8),
"RX Date--Dx/Stg Proc Flag" varchar2(2),
"RX Summ--Treatment Status" varchar2(1),
"RX Summ--Surg Prim Site" varchar2(2),
"RX Summ--Scope Reg LN Sur" varchar2(1),
"RX Summ--Surg Oth Reg/Dis" varchar2(1),
"RX Summ--Reg LN Examined" varchar2(2),
"RX Summ--Surgical Approch" varchar2(1),
"RX Summ--Surgical Margins" varchar2(1),
"RX Summ--Reconstruct 1st" varchar2(1),
"Reason for No Surgery" varchar2(1),
"RX Summ--DX/Stg Proc" varchar2(2),
"RX Summ--Palliative Proc" varchar2(1),
"RX Summ--Radiation" varchar2(1),
"RX Summ--Rad to CNS" varchar2(1),
"RX Summ--Surg/Rad Seq" varchar2(1),
"RX Summ--Transplnt/Endocr" varchar2(2),
"RX Summ--Chemo" varchar2(2),
"RX Summ--Hormone" varchar2(2),
"RX Summ--BRM" varchar2(2),
"RX Summ--Other" varchar2(1),
"Reason for No Radiation" varchar2(1),
"RX Coding System--Current" varchar2(2),
"First Course Calc Method" varchar2(1),
"Rad--Regional Dose: CGY" varchar2(5),
"Rad--No of Treatment Vol" varchar2(3),
"Rad--Treatment Volume" varchar2(2),
"Rad--Location of RX" varchar2(1),
"Rad--Regional RX Modality" varchar2(2),
"Rad--Boost RX Modality" varchar2(2),
"Rad--Boost Dose cGy" varchar2(5),
"RX Summ--Systemic/Sur Seq" varchar2(1),
"RX Summ--Surgery Type" varchar2(2),
"Readm Same Hosp 30 Days" varchar2(1),
"RX Summ--Surg Site 98-02" varchar2(2),
"RX Summ--Scope Reg 98-02" varchar2(1),
"RX Summ--Surg Oth 98-02" varchar2(1),
"Reserved 06" varchar2(100),
"Subsq RX 2nd Course Date" varchar2(8),
"Subsq RX 2ndCrs Date Flag" varchar2(2),
"Subsq RX 2nd Course Codes" varchar2(11),
"Subsq RX 2nd Course Surg" varchar2(2),
"Subsq RX 2nd--Scope LN SU" varchar2(1),
"Subsq RX 2nd--Surg Oth" varchar2(1),
"Subsq RX 2nd--Reg LN Rem" varchar2(2),
"Subsq RX 2nd Course Rad" varchar2(1),
"Subsq RX 2nd Course Chemo" varchar2(1),
"Subsq RX 2nd Course Horm" varchar2(1),
"Subsq RX 2nd Course BRM" varchar2(1),
"Subsq RX 2nd Course Oth" varchar2(1),
"Subsq RX 3rd Course Date" varchar2(8),
"Subsq RX 3rdCrs Date Flag" varchar2(2),
"Subsq RX 3rd Course Codes" varchar2(11),
"Subsq RX 3rd Course Surg" varchar2(2),
"Subsq RX 3rd--Scope LN Su" varchar2(1),
"Subsq RX 3rd--Surg Oth" varchar2(1),
"Subsq RX 3rd--Reg LN Rem" varchar2(2),
"Subsq RX 3rd Course Rad" varchar2(1),
"Subsq RX 3rd Course Chemo" varchar2(1),
"Subsq RX 3rd Course Horm" varchar2(1),
"Subsq RX 3rd Course BRM" varchar2(1),
"Subsq RX 3rd Course Oth" varchar2(1),
"Subsq RX 4th Course Date" varchar2(8),
"Subsq RX 4thCrs Date Flag" varchar2(2),
"Subsq RX 4th Course Codes" varchar2(11),
"Subsq RX 4th Course Surg" varchar2(2),
"Subsq RX 4th--Scope LN Su" varchar2(1),
"Subsq RX 4th--Surg Oth" varchar2(1),
"Subsq RX 4th--Reg LN Rem" varchar2(2),
"Subsq RX 4th Course Rad" varchar2(1),
"Subsq RX 4th Course Chemo" varchar2(1),
"Subsq RX 4th Course Horm" varchar2(1),
"Subsq RX 4th Course BRM" varchar2(1),
"Subsq RX 4th Course Oth" varchar2(1),
"Subsq RX--Reconstruct Del" varchar2(1),
"Reserved 07" varchar2(100),
"Over-ride SS/NodesPos" varchar2(1),
"Over-ride SS/TNM-N" varchar2(1),
"Over-ride SS/TNM-M" varchar2(1),
"Over-ride Acsn/Class/Seq" varchar2(1),
"Over-ride HospSeq/DxConf" varchar2(1),
"Over-ride CoC-Site/Type" varchar2(1),
"Over-ride HospSeq/Site" varchar2(1),
"Over-ride Site/TNM-StgGrp" varchar2(1),
"Over-ride Age/Site/Morph" varchar2(1),
"Over-ride SeqNo/DxConf" varchar2(1),
"Over-ride Site/Lat/SeqNo" varchar2(1),
"Over-ride Surg/DxConf" varchar2(1),
"Over-ride Site/Type" varchar2(1),
"Over-ride Histology" varchar2(1),
"Over-ride Report Source" varchar2(1),
"Over-ride Ill-define Site" varchar2(1),
"Over-ride Leuk, Lymphoma" varchar2(1),
"Over-ride Site/Behavior" varchar2(1),
"Over-ride Site/EOD/DX Dt" varchar2(1),
"Over-ride Site/Lat/EOD" varchar2(1),
"Over-ride Site/Lat/Morph" varchar2(1),
"Site (73-91) ICD-O-1" varchar2(4),
"Morph (73-91) ICD-O-1" varchar2(6),
"Histology (73-91) ICD-O-1" varchar2(4),
"Behavior (73-91) ICD-O-1" varchar2(1),
"Grade (73-91) ICD-O-1" varchar2(1),
"ICD-O-2 Conversion Flag" varchar2(1),
"CRC CHECKSUM" varchar2(10),
"SEER Coding Sys--Current" varchar2(1),
"SEER Coding Sys--Original" varchar2(1),
"CoC Coding Sys--Current" varchar2(2),
"CoC Coding Sys--Original" varchar2(2),
"Vendor Name" varchar2(10),
"SEER Type of Follow-Up" varchar2(1),
"SEER Record Number" varchar2(2),
"Diagnostic Proc 73-87" varchar2(2),
"Date Case Initiated" varchar2(8),
"Date Case Completed" varchar2(8),
"Date Case Completed--CoC" varchar2(8),
"Date Case Last Changed" varchar2(8),
"Date Case Report Exported" varchar2(8),
"Date Case Report Received" varchar2(8),
"Date Case Report Loaded" varchar2(8),
"Date Tumor Record Availbl" varchar2(8),
"ICD-O-3 Conversion Flag" varchar2(1),
"Over-ride CS 1" varchar2(1),
"Over-ride CS 2" varchar2(1),
"Over-ride CS 3" varchar2(1),
"Over-ride CS 4" varchar2(1),
"Over-ride CS 5" varchar2(1),
"Over-ride CS 6" varchar2(1),
"Over-ride CS 7" varchar2(1),
"Over-ride CS 8" varchar2(1),
"Over-ride CS 9" varchar2(1),
"Over-ride CS 10" varchar2(1),
"Over-ride CS 11" varchar2(1),
"Over-ride CS 12" varchar2(1),
"Over-ride CS 13" varchar2(1),
"Over-ride CS 14" varchar2(1),
"Over-ride CS 15" varchar2(1),
"Over-ride CS 16" varchar2(1),
"Over-ride CS 17" varchar2(1),
"Over-ride CS 18" varchar2(1),
"Over-ride CS 19" varchar2(1),
"Over-ride CS 20" varchar2(1),
"Reserved 08" varchar2(80),
"Date of Last Contact" varchar2(8),
"Date of Last Contact Flag" varchar2(2),
"Vital Status" varchar2(1),
"Cancer Status" varchar2(1),
"Quality of Survival" varchar2(1),
"Follow-Up Source" varchar2(1),
"Next Follow-Up Source" varchar2(1),
"Addr Current--City" varchar2(50),
"Addr Current--State" varchar2(2),
"Addr Current--Postal Code" varchar2(9),
"County--Current" varchar2(3),
"Unusual Follow-Up Method" varchar2(1),
"Recurrence Date--1st" varchar2(8),
"Recurrence Date--1st Flag" varchar2(2),
"Recurrence Type--1st" varchar2(2),
"Follow-Up Contact--City" varchar2(50),
"Follow-Up Contact--State" varchar2(2),
"Follow-Up Contact--Postal" varchar2(9),
"Cause of Death" varchar2(4),
"ICD Revision Number" varchar2(1),
"Autopsy" varchar2(1),
"Place of Death" varchar2(3),
"Follow-up Source Central" varchar2(2),
"Date of Death--Canada" varchar2(8),
"Date of Death--CanadaFlag" varchar2(2),
"Reserved 09" varchar2(50),
"State/Requestor Items" varchar2(1000),
"Name--Last" varchar2(40),
"Name--First" varchar2(40),
"Name--Middle" varchar2(40),
"Name--Prefix" varchar2(3),
"Name--Suffix" varchar2(3),
"Name--Alias" varchar2(40),
"Name--Maiden" varchar2(40),
"Name--Spouse/Parent" varchar2(60),
"Medical Record Number" varchar2(11),
"Military Record No Suffix" varchar2(2),
"Social Security Number" varchar2(9),
"Addr at DX--No & Street" varchar2(60),
"Addr at DX--Supplementl" varchar2(60),
"Addr Current--No & Street" varchar2(60),
"Addr Current--Supplementl" varchar2(60),
"Telephone" varchar2(10),
"DC State File Number" varchar2(6),
"Follow-Up Contact--Name" varchar2(60),
"Follow-Up Contact--No&St" varchar2(60),
"Follow-Up Contact--Suppl" varchar2(60),
"Latitude" varchar2(10),
"Longitude" varchar2(11),
"Reserved 10" varchar2(200),
"NPI--Following Registry" varchar2(10),
"Following Registry" varchar2(10),
"NPI--Inst Referred From" varchar2(10),
"Institution Referred From" varchar2(10),
"NPI--Inst Referred To" varchar2(10),
"Institution Referred To" varchar2(10),
"Reserved 11" varchar2(50),
"NPI--Physician--Managing" varchar2(10),
"Physician--Managing" varchar2(8),
"NPI--Physician--Follow-Up" varchar2(10),
"Physician--Follow-Up" varchar2(8),
"NPI--Physician--Primary Surg" varchar2(10),
"Physician--Primary Surg" varchar2(8),
"NPI--Physician 3" varchar2(10),
"Physician 3" varchar2(8),
"NPI--Physician 4" varchar2(10),
"Physician 4" varchar2(8),
"Reserved 12" varchar2(50),
"Path Reporting Fac ID 1" varchar2(25),
"Path Report Number 1" varchar2(20),
"Path Date Spec Collect 1" varchar2(14),
"Path Report Type 1" varchar2(2),
"Path Ordering Fac No 1" varchar2(25),
"Path Order Phys Lic No 1" varchar2(20),
"Path Reporting Fac ID 2" varchar2(25),
"Path Report Number 2" varchar2(20),
"Path Date Spec Collect 2" varchar2(14),
"Path Report Type 2" varchar2(2),
"Path Ordering Fac No 2" varchar2(25),
"Path Order Phys Lic No 2" varchar2(20),
"Path Reporting Fac ID 3" varchar2(25),
"Path Report Number 3" varchar2(20),
"Path Date Spec Collect 3" varchar2(14),
"Path Report Type 3" varchar2(2),
"Path Ordering Fac No 3" varchar2(25),
"Path Order Phys Lic No 3" varchar2(20),
"Path Reporting Fac ID 4" varchar2(25),
"Path Report Number 4" varchar2(20),
"Path Date Spec Collect 4" varchar2(14),
"Path Report Type 4" varchar2(2),
"Path Ordering Fac No 4" varchar2(25),
"Path Order Phys Lic No 4" varchar2(20),
"Path Reporting Fac ID 5" varchar2(25),
"Path Report Number 5" varchar2(20),
"Path Date Spec Collect 5" varchar2(14),
"Path Report Type 5" varchar2(2),
"Path Ordering Fac No 5" varchar2(25),
"Path Order Phys Lic No 5" varchar2(20),
"Reserved 13" varchar2(500),
"Text--DX Proc--PE" varchar2(1000),
"Text--DX Proc--X-ray/Scan" varchar2(1000),
"Text--DX Proc--Scopes" varchar2(1000),
"Text--DX Proc--Lab Tests" varchar2(1000),
"Text--DX Proc--Op" varchar2(1000),
"Text--DX Proc--Path" varchar2(1000),
"Text--Primary Site Title" varchar2(100),
"Text--Histology Title" varchar2(100),
"Text--Staging" varchar2(1000),
"RX Text--Surgery" varchar2(1000),
"RX Text--Radiation (Beam)" varchar2(1000),
"RX Text--Radiation Other" varchar2(1000),
"RX Text--Chemo" varchar2(1000),
"RX Text--Hormone" varchar2(1000),
"RX Text--BRM" varchar2(1000),
"RX Text--Other" varchar2(1000),
"Text--Remarks" varchar2(1000),
"Text--Place of Diagnosis" varchar2(60),
"Reserved 14" varchar2(2000)
)
;
