# Stubs for luigi.event (Python 3.5)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

class Event:
    DEPENDENCY_DISCOVERED = ...  # type: str
    DEPENDENCY_MISSING = ...  # type: str
    DEPENDENCY_PRESENT = ...  # type: str
    BROKEN_TASK = ...  # type: str
    START = ...  # type: str
    FAILURE = ...  # type: str
    SUCCESS = ...  # type: str
    PROCESSING_TIME = ...  # type: str
    TIMEOUT = ...  # type: str
    PROCESS_FAILURE = ...  # type: str
