# Stubs for luigi.interface (Python 3.5)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any, Optional
from . import task

def setup_interface_logging(conf_file: str = ..., level_name: str = ...): ...

class core(task.Config):
    use_cmdline_section = ...  # type: bool
    local_scheduler = ...  # type: Any
    scheduler_host = ...  # type: Any
    scheduler_port = ...  # type: Any
    scheduler_url = ...  # type: Any
    lock_size = ...  # type: Any
    no_lock = ...  # type: Any
    lock_pid_dir = ...  # type: Any
    take_lock = ...  # type: Any
    workers = ...  # type: Any
    logging_conf_file = ...  # type: Any
    log_level = ...  # type: Any
    module = ...  # type: Any
    parallel_scheduling = ...  # type: Any
    assistant = ...  # type: Any
    help = ...  # type: Any
    help_all = ...  # type: Any

class _WorkerSchedulerFactory:
    def create_local_scheduler(self): ...
    def create_remote_scheduler(self, url): ...
    def create_worker(self, scheduler, worker_processes, assistant: bool = ...): ...

class PidLockAlreadyTakenExit(SystemExit): ...

def run(*args, **kwargs): ...
def build(tasks, worker_scheduler_factory: Optional[Any] = ..., **env_params): ...
