# Stubs for docopt (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any, Dict, List, Optional

def docopt(doc: str, argv: Optional[List[str]] = ..., help: bool = ..., version: Optional[Any] = ..., options_first: bool = ...) -> Dict[str, str]: ...
